Add controllers
VVish1337/java-shareit pull request #2
Opened 2022-08-18 10:57 UTC by VVish1337

#Sprint 1

2022-08-19 11:15 UTC, Fleaman777 requested changes

2022-08-19 11:15 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +        return itemsList;
этот метод тоже хорошобудет выглядеть через стрим

посмотри другие подобные места, может получится еще что улучшить

2022-08-19 11:15 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/requests/ItemRequest.java
>   * // TODO .
название пакета должно быть в единтсвенном числе

2022-08-19 11:15 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +}
этот класс хоть пока и не используется но уже можно заполнить необходимыми полями

2022-08-19 11:32 UTC, VVish1337 commented on src/main/java/ru/practicum/shareit/requests/ItemRequest.java
>   * // TODO .
Название пакетов requests и booking были уже в проекте я их не создавал точной информации по ним нет.

2022-08-19 11:32 UTC, VVish1337 commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +}
Так как у меня нет на него полной информации я не могу точно его заполнить он был создан не мной а уже был в проекте.

2022-08-20 08:06 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/requests/ItemRequest.java
>   * // TODO .
Окей

2022-08-20 08:06 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +}
Окей

2022-08-26 08:30 UTC, merged