Sprint #2
VVish1337/java-shareit pull request #3
Opened 2022-09-09 13:27 UTC by VVish1337

2022-09-10 08:27 UTC, Fleaman777 requested changes

2022-09-10 08:27 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/mapper/BookingMapper.java
> +        booking.setStatus(BookingStatus.WAITING);
когда в одном объекте нужно просетать много полей, хорошо использовать билдер

применимо ко всем похожим местам

2022-09-10 08:27 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    List<Booking> findBookingsByItemOwnerCurrent(Long userId, LocalDateTime now);
а через синтаксис spring jpa(так, как сделаны методы ниже) не пробовал написать эти методы ? или через query лучше вышло?

2022-09-10 08:27 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            throw new ItemUnavailableException("Booking start is after end");
в случае, когда валидация не проходит, можно добавить логирование

2022-09-10 08:27 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            throw new ItemUnavailableException("Booking items for comments not found");
здесь тоже можно добавить логирование, 
аналагично во всех похожих местах

2022-09-10 08:27 UTC, Fleaman777 commented on src/main/resources/schema.sql
> +    start_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
как вариант немного проапргейрдить таблицу, можно было бы еще добавить просеичвание дефолтного времени

2022-09-11 09:10 UTC, VVish1337 commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    List<Booking> findBookingsByItemOwnerCurrent(Long userId, LocalDateTime now);
Название метода слишком длинное получится

2022-09-12 11:20 UTC, Fleaman777 approved these changes

2022-09-13 08:37 UTC, merged