#Sprint 3
VVish1337/java-shareit pull request #4
Opened 2022-09-22 09:03 UTC by VVish1337

2022-09-22 17:58 UTC, VVish1337 commented on pom.xml
> +												<minimum>0.53</minimum>
Я написал все тесты на методы но на brunch 0.6 набрать не смог если ты не против уменьшил до 0.53 Владимир вроде разрешил так сделать если основные тесты написаны.

2022-09-23 16:39 UTC, Fleaman777 requested changes

2022-09-23 16:39 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    private Pageable pageable;
нет необходимости pagable делать полем класса, т.к. все равно в каждом методе значение pagable будет свое

2022-09-23 16:39 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        pageable = PageRequest.of(from / size, size, sort);
логику по получению pagable можно вынести в отдельный метод

2022-09-23 16:39 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +                .build();
отлично, правильный подход с тем, что бы большое количество полей просечивать через билдер

2022-09-23 16:39 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/controller/BookingControllerTest.java
> +    MockMvc mvc;
в тестах тоже лучше придерживаться принципа инкапсуляции, и поля делать private

2022-09-23 16:39 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/controller/BookingControllerTest.java
> +    void createBookingPost200() throws Exception {
неплохое у тебя название,

но есть еще 1 варинат, с наиболее оптимальной формой названия тест методов, выглядит примерно так: 
shouldReturn200OnPostCreateBooking
в случае, если какие-то доп условия 
shouldReturn200OnPostCreateBookingIf.....

2022-09-23 16:39 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/mapper/BookingMapperTest.java
> +    }
отличный метод, всю необходимую логику инициализации вынес в него

2022-09-23 16:39 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/service/BookingServiceTest.java
> +        userRepository = mock(UserRepository.class);
как еще один вариант создать мок класса, использовать аннотацию @Mock, 
а что бы все моки проинжектить в тестируемыц класс, можно использовать аннотацию @InjectMocks

2022-09-23 16:39 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/exception/ErrorHandlerTest.java
> +class ErrorHandlerTest {
здорово конечно, что ты реши протестировать и этот класс, но на самом деле не обязательно, 
т.к. по сути, в нем используется только логика которая была в библиотеке, а нашей кастомной логики, которую можно протестировать, почти нет

2022-09-23 16:39 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/item/controller/ItemControllerTest.java
> +                        .accept(MediaType.APPLICATION_JSON))
общую, для всех тест-методов, часть можно было бы вынести в отдельный метод с нужными аргументами

аналагично в похожих местах

2022-09-23 16:39 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/item/service/ItemServiceTest.java
> +    void createCommentThrowException() {
можно в название метода добавить, почему именно выбрасывается эксепшен 
createCommentThrowExceptionIf.....

так будет чуть легче понять, почему выбрасывается исключение, не заглядывая в сам тест

2022-09-23 16:39 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/request/controller/ItemRequestControllerTest.java
> +    MockMvc mvc;
поля должны быть private

2022-09-24 13:50 UTC, VVish1337 commented on src/test/java/ru/practicum/shareit/exception/ErrorHandlerTest.java
> +class ErrorHandlerTest {
Для jococo не хватало тест по классам пройти

2022-09-25 19:53 UTC, Fleaman777 approved these changes

2022-09-25 19:53 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/util/PaginationUtil.java
> +}
хороший подход

2022-09-25 19:55 UTC, Fleaman777 commented on pom.xml
> +												<minimum>0.53</minimum>
хорошо, понял, 
ну да, основные кейсы покрыты, можешь оставить 0,53

2022-09-28 07:06 UTC, merged